name: Learn C Exercises CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up the C compiler
    - name: Setup Build Essentials
      run: sudo apt-get install -y build-essential

    - name: Build all exercises
      working-directory: learn-c/
      run: |
        for dir in $(find . -maxdepth 1 -type d | tail -n +2); do
          echo "##[group]Processing $dir"
          cd "$dir"
          echo "Building project in $dir"
          make build
          echo "Done, moving on..."
          cd ..
          echo "##[endgroup]"
        done

    - name: Run all exercises
      working-directory: learn-c/
      run: |
        for dir in $(find . -maxdepth 1 -type d | tail -n +2); do
          echo "##[group]Processing $dir"
          cd "$dir"
          echo "Running project in $dir"
          make run
          echo "Done, moving on..."
          cd ..
          echo "##[endgroup]"
        done
